// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Event emitted when the reflection layer evaluates task completion.
 */
export type ReflectionVerdictEvent = { 
/**
 * Whether the task was completed successfully.
 */
completed: boolean, 
/**
 * Confidence score from 0.0 to 1.0.
 */
confidence: number, 
/**
 * The judge's reasoning for the verdict.
 */
reasoning: string, 
/**
 * Feedback for incomplete tasks (None if completed).
 */
feedback: string | null, 
/**
 * Current reflection attempt number.
 */
attempt: number, 
/**
 * Maximum allowed attempts.
 */
max_attempts: number, };
